model:
  model_name_or_path: "<model_name>"
  tokenizer_name: null
  cache_dir: "/root/autodl-tmp/data/v.moskvoretskii/cache/"
  trust_remote_code: false
  use_fast_tokenizer: true
  torch_dtype: "bfloat16"

data:
  dataset_name: "data/datasets/s_nq"
  block_size: 1024
  validation_split_percentage: 0
  dataset_percentage: 100
  seed: 42
  streaming: false
  overwrite_cache: false
  preprocessing_num_workers: 4
  load_from_disk: true

training:
  output_dir: "./my-finetuned-llama-fsdp" # STaR overwrites it
  learning_rate: 7.0e-6
  num_train_epochs: 1
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 4
  gradient_checkpointing: false
  max_steps: -1
  save_strategy: "no"
  save_steps: 1
  evaluation_strategy: "no"
  eval_steps: 1
  weight_decay: 0.1
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"
  logging_steps: 10
  do_train: true
  do_eval: false
  report_to: ["wandb"]
  run_name: "test_STaR"
  project_name: "STaR"

peft:
  use_lora: false
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.1
  lora_target_modules:
    - "query_key_value"
  dora: false
